.TH MYGREP 1 "September 2026" "OS Assignment" "User Commands"
.SH NAME
mygrep \- search for a string in a file
.SH SYNOPSIS
.B #include "myfilefunctions.h"
.br
.B int mygrep(const char *filename, const char *pattern);
.SH DESCRIPTION
The
.B mygrep
function searches the specified file for occurrences of the given pattern.
It returns the result of the search according to whether the pattern is found.
.SH AUTHOR
Farya Azhar <farii229900@gmail.com>
