.TH MYSTRNCPY 1 "September 2026" "OS Assignment" "User Commands"
.SH NAME
mystrncpy \- copy a specified number of characters from one string to another
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.br
.B char *mystrncpy(char *destination, const char *source, int n);
.SH DESCRIPTION
The
.B mystrncpy
function copies up to
.B n
characters from the source string to the destination string.
It is useful when only a specified number of characters need to be copied.
.SH AUTHOR
Farya Azhar <farii229900@gmail.com>
