.TH MYSTRLEN 1 "September 2026" "OS Assignment" "User Commands"
.SH NAME
mystrlen \- calculate the length of a string
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.br
.B int mystrlen(const char *str);
.SH DESCRIPTION
The
.B mystrlen
function calculates and returns the number of characters in the given string.
The null terminating character is not included in the returned length.
.SH AUTHOR
Farya Azhar <farii229900@gmail.com>
