.TH MYSTRCAT 1 "September 2026" "OS Assignment" "User Commands"
.SH NAME
mystrcat \- concatenate two strings
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.br
.B char *mystrcat(char *destination, const char *source);
.SH DESCRIPTION
The
.B mystrcat
function appends the source string to the end of the destination string.
The destination string must have enough space to contain both strings.
.SH AUTHOR
Farya Azhar <farii229900@gmail.com>
