.TH MYSTRCPY 1 "September 2026" "OS Assignment" "User Commands"
.SH NAME
mystrcpy \- copy a string to another string
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.br
.B char *mystrcpy(char *destination, const char *source);
.SH DESCRIPTION
The
.B mystrcpy
function copies the characters from the source string into the destination string.
The destination string is expected to have enough space to store the copied string.
.SH AUTHOR
Farya Azhar <farii229900@gmail.com>
