.TH WORDCOUNT 1 "September 2026" "OS Assignment" "User Commands"
.SH NAME
wordCount \- count the number of words in a file
.SH SYNOPSIS
.B #include "myfilefunctions.h"
.br
.B int wordCount(const char *filename);
.SH DESCRIPTION
The
.B wordCount
function reads the specified file and counts the number of words contained in it.
It returns the total number of words found in the file.
.SH AUTHOR
Farya Azhar <farii229900@gmail.com>
